<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class XAccessiMenu
    Inherits DXBASE.XWinBase

    'Form esegue l'override del metodo Dispose per pulire l'elenco dei componenti.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Richiesto da Progettazione Windows Form
    Private components As System.ComponentModel.IContainer

    'NOTA: la procedura che segue è richiesta da Progettazione Windows Form
    'Può essere modificata in Progettazione Windows Form.  
    'Non modificarla nell'editor del codice.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(XAccessiMenu))
        Me.MenuStrip1 = New System.Windows.Forms.MenuStrip
        Me.SuspendLayout()
        '
        'ImageList32
        '
        Me.ImageList32.ImageStream = CType(resources.GetObject("ImageList32.ImageStream"), System.Windows.Forms.ImageListStreamer)
        Me.ImageList32.Images.SetKeyName(0, "")
        Me.ImageList32.Images.SetKeyName(1, "")
        Me.ImageList32.Images.SetKeyName(2, "")
        Me.ImageList32.Images.SetKeyName(3, "")
        Me.ImageList32.Images.SetKeyName(4, "")
        Me.ImageList32.Images.SetKeyName(5, "")
        Me.ImageList32.Images.SetKeyName(6, "")
        Me.ImageList32.Images.SetKeyName(7, "")
        Me.ImageList32.Images.SetKeyName(8, "")
        Me.ImageList32.Images.SetKeyName(9, "")
        Me.ImageList32.Images.SetKeyName(10, "")
        Me.ImageList32.Images.SetKeyName(11, "")
        Me.ImageList32.Images.SetKeyName(12, "")
        Me.ImageList32.Images.SetKeyName(13, "")
        Me.ImageList32.Images.SetKeyName(14, "")
        Me.ImageList32.Images.SetKeyName(15, "")
        Me.ImageList32.Images.SetKeyName(16, "")
        Me.ImageList32.Images.SetKeyName(17, "")
        Me.ImageList32.Images.SetKeyName(18, "")
        Me.ImageList32.Images.SetKeyName(19, "")
        Me.ImageList32.Images.SetKeyName(20, "")
        Me.ImageList32.Images.SetKeyName(21, "")
        Me.ImageList32.Images.SetKeyName(22, "")
        Me.ImageList32.Images.SetKeyName(23, "")
        Me.ImageList32.Images.SetKeyName(24, "")
        Me.ImageList32.Images.SetKeyName(25, "")
        Me.ImageList32.Images.SetKeyName(26, "")
        Me.ImageList32.Images.SetKeyName(27, "")
        Me.ImageList32.Images.SetKeyName(28, "mainicon.ico")
        '
        'ImageListXP_32
        '
        'Me.ImageListXP_32.ImageStream = CType(resources.GetObject("ImageListXP_32.ImageStream"), System.Windows.Forms.ImageListStreamer)
        'Me.ImageListXP_32.Images.SetKeyName(0, "Documents.ico")
        'Me.ImageListXP_32.Images.SetKeyName(1, "3.ico")
        'Me.ImageListXP_32.Images.SetKeyName(2, "4.ico")
        'Me.ImageListXP_32.Images.SetKeyName(3, "29.ico")
        'Me.ImageListXP_32.Images.SetKeyName(4, "67.ico")
        'Me.ImageListXP_32.Images.SetKeyName(5, "73.ico")
        'Me.ImageListXP_32.Images.SetKeyName(6, "49.ico")
        'Me.ImageListXP_32.Images.SetKeyName(7, "51.ico")
        'Me.ImageListXP_32.Images.SetKeyName(8, "46.ico")
        'Me.ImageListXP_32.Images.SetKeyName(9, "Run.ico")
        'Me.ImageListXP_32.Images.SetKeyName(10, "Default Document.ico")
        'Me.ImageListXP_32.Images.SetKeyName(11, "58.ico")
        'Me.ImageListXP_32.Images.SetKeyName(12, "Workgroup.ico")
        'Me.ImageListXP_32.Images.SetKeyName(13, "1.ico")
        'Me.ImageListXP_32.Images.SetKeyName(14, "2.ico")
        'Me.ImageListXP_32.Images.SetKeyName(15, "6.ico")
        'Me.ImageListXP_32.Images.SetKeyName(16, "30.ico")
        'Me.ImageListXP_32.Images.SetKeyName(17, "41.ico")
        'Me.ImageListXP_32.Images.SetKeyName(18, "43.ico")
        'Me.ImageListXP_32.Images.SetKeyName(19, "48.ico")
        'Me.ImageListXP_32.Images.SetKeyName(20, "59.ico")
        'Me.ImageListXP_32.Images.SetKeyName(21, "62.ico")
        'Me.ImageListXP_32.Images.SetKeyName(22, "64.ico")
        'Me.ImageListXP_32.Images.SetKeyName(23, "66.ico")
        'Me.ImageListXP_32.Images.SetKeyName(24, "69.ico")
        'Me.ImageListXP_32.Images.SetKeyName(25, "85.ico")
        'Me.ImageListXP_32.Images.SetKeyName(26, "86.ico")
        'Me.ImageListXP_32.Images.SetKeyName(27, "88.ico")
        'Me.ImageListXP_32.Images.SetKeyName(28, "91.ico")
        'Me.ImageListXP_32.Images.SetKeyName(29, "Administrative Tools.ico")
        'Me.ImageListXP_32.Images.SetKeyName(30, "CD-ROM Drive.ico")
        'Me.ImageListXP_32.Images.SetKeyName(31, "Closed Folder.ico")
        'Me.ImageListXP_32.Images.SetKeyName(32, "Control Panel.ico")
        'Me.ImageListXP_32.Images.SetKeyName(33, "Find.ico")
        'Me.ImageListXP_32.Images.SetKeyName(34, "Hard Drive.ico")
        'Me.ImageListXP_32.Images.SetKeyName(35, "Help.ico")
        'Me.ImageListXP_32.Images.SetKeyName(36, "In Box.ico")
        'Me.ImageListXP_32.Images.SetKeyName(37, "My Computer.ico")
        'Me.ImageListXP_32.Images.SetKeyName(38, "Open Folder.ico")
        'Me.ImageListXP_32.Images.SetKeyName(39, "Printers.ico")
        'Me.ImageListXP_32.Images.SetKeyName(40, "Recycle Bin (empty).ico")
        'Me.ImageListXP_32.Images.SetKeyName(41, "Recycle Bin (full).ico")
        'Me.ImageListXP_32.Images.SetKeyName(42, "Subscriptions.ico")
        'Me.ImageListXP_32.Images.SetKeyName(43, "Text Document.ico")
        'Me.ImageListXP_32.Images.SetKeyName(44, "The Internet.ico")
        'Me.ImageListXP_32.Images.SetKeyName(45, "Url History.ico")
        'Me.ImageListXP_32.Images.SetKeyName(46, "Stampa.ico")
        'Me.ImageListXP_32.Images.SetKeyName(47, "Pulisci.ico")
        'Me.ImageListXP_32.Images.SetKeyName(48, "none.ico")
        'Me.ImageListXP_32.Images.SetKeyName(49, "search4printer.ico")
        'Me.ImageListXP_32.Images.SetKeyName(50, "search4files.ico")
        'Me.ImageListXP_32.Images.SetKeyName(51, "search4people.ico")
        'Me.ImageListXP_32.Images.SetKeyName(52, "users.ico")
        'Me.ImageListXP_32.Images.SetKeyName(53, "search.ico")
        'Me.ImageListXP_32.Images.SetKeyName(54, "propertiesORoptions.ico")
        'Me.ImageListXP_32.Images.SetKeyName(55, "user.ico")
        'Me.ImageListXP_32.Images.SetKeyName(56, "search4doc.ico")
        'Me.ImageListXP_32.Images.SetKeyName(57, "searchweb.ico")
        'Me.ImageListXP_32.Images.SetKeyName(58, "disconnect3.ico")
        'Me.ImageListXP_32.Images.SetKeyName(59, "repair.ico")
        'Me.ImageListXP_32.Images.SetKeyName(60, "delete_16x.ico")
        'Me.ImageListXP_32.Images.SetKeyName(61, "disconnect2.ico")
        'Me.ImageListXP_32.Images.SetKeyName(62, "fax.ico")
        'Me.ImageListXP_32.Images.SetKeyName(63, "mobsync.20.ico")
        '
        'ImageGly
        '
        Me.ImageGly.ImageStream = CType(resources.GetObject("ImageGly.ImageStream"), System.Windows.Forms.ImageListStreamer)
        Me.ImageGly.Images.SetKeyName(0, "")
        Me.ImageGly.Images.SetKeyName(1, "")
        Me.ImageGly.Images.SetKeyName(2, "")
        Me.ImageGly.Images.SetKeyName(3, "")
        Me.ImageGly.Images.SetKeyName(4, "")
        Me.ImageGly.Images.SetKeyName(5, "")
        Me.ImageGly.Images.SetKeyName(6, "")
        Me.ImageGly.Images.SetKeyName(7, "")
        Me.ImageGly.Images.SetKeyName(8, "")
        Me.ImageGly.Images.SetKeyName(9, "")
        Me.ImageGly.Images.SetKeyName(10, "")
        Me.ImageGly.Images.SetKeyName(11, "Red Checkmark 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(12, "Blue Checkmark 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(13, "Green Checkmark 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(14, "Add Document 4 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(15, "Help - Lifesaver 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(16, "Delete Selection 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(17, "Options 3 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(18, "Trash Plastic Full 2 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(19, "Paintbrush and Document 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(20, "View Documents 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(21, "Print Preview 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(22, "Import to Database 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(23, "Locked 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(24, "Unlocked 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(25, "Forward Mail 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(26, "Fax Machine 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(27, "Spy with Hat 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(28, "Import Doc 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(29, "Open File or Folder 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(30, "Hard Hat Male 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(31, "Replace 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(32, "Export from Database 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(33, "View User 3 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(34, "Add User 3 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(35, "Truck 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(36, "BARCODE.ico")
        Me.ImageGly.Images.SetKeyName(37, "Organizer - Delete 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(38, "Organizer - Edit 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(39, "Red Plus 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(40, "Red Minus 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(41, "Cellphone 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(42, "Exit Door 2 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(43, "Cellphone 2 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(44, "Scan Document 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(45, "News Blue 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(46, "Emails 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(47, "Refresh Document 32 h i32.ico")
        Me.ImageGly.Images.SetKeyName(48, "Gavel 32 h i32.ico")
        '
        'imageList1
        '
        Me.imageList1.ImageStream = CType(resources.GetObject("imageList1.ImageStream"), System.Windows.Forms.ImageListStreamer)
        Me.imageList1.Images.SetKeyName(0, "")
        Me.imageList1.Images.SetKeyName(1, "")
        Me.imageList1.Images.SetKeyName(2, "")
        Me.imageList1.Images.SetKeyName(3, "")
        Me.imageList1.Images.SetKeyName(4, "")
        Me.imageList1.Images.SetKeyName(5, "")
        Me.imageList1.Images.SetKeyName(6, "")
        Me.imageList1.Images.SetKeyName(7, "")
        Me.imageList1.Images.SetKeyName(8, "")
        Me.imageList1.Images.SetKeyName(9, "Red Delete 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(10, "")
        Me.imageList1.Images.SetKeyName(11, "")
        Me.imageList1.Images.SetKeyName(12, "")
        Me.imageList1.Images.SetKeyName(13, "")
        Me.imageList1.Images.SetKeyName(14, "")
        Me.imageList1.Images.SetKeyName(15, "")
        Me.imageList1.Images.SetKeyName(16, "")
        Me.imageList1.Images.SetKeyName(17, "")
        Me.imageList1.Images.SetKeyName(18, "")
        Me.imageList1.Images.SetKeyName(19, "")
        Me.imageList1.Images.SetKeyName(20, "")
        Me.imageList1.Images.SetKeyName(21, "")
        Me.imageList1.Images.SetKeyName(22, "")
        Me.imageList1.Images.SetKeyName(23, "")
        Me.imageList1.Images.SetKeyName(24, "Green Checkmark 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(25, "Blue Checkmark 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(26, "Green Plus 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(27, "Stop Sign 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(28, "Red Checkmark 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(29, "Cargo Ship 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(30, "Red Minus 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(31, "OK 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(32, "Blue Arrow Down 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(33, "Blue Arrow Up 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(34, "Blue Arrow NE 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(35, "Red Arrow Down 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(36, "Red Arrow Up 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(37, "Red Arrow NE 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(38, "Blue Delete 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(39, "Circle Yellow 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(40, "Lightning 1 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(41, "Pulisci.ico")
        Me.imageList1.Images.SetKeyName(42, "Circle Red 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(43, "Handshake 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(44, "Paintbrush and Document 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(45, "Hard Hat Male 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(46, "Credit Card - Gold 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(47, "Money 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(48, "View User 3 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(49, "User Group 2 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(50, "Export from Database 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(51, "Database Rollback 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(52, "Undo 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(53, "Home 2 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(54, "Note 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(55, "Green Arrow Left 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(56, "Red Arrow Right 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(57, "Parcel and Label 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(58, "Pin Black 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(59, "Cellphone 2 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(60, "Cellphone 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(61, "Organizer - Edit 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(62, "Pdf16.bmp")
        Me.imageList1.Images.SetKeyName(63, "Light Red Round 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(64, "Light Green Round 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(65, "Light Purple Round 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(66, "Pin Green 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(67, "Pin Red 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(68, "Pin Purple 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(69, "Scan Document 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(70, "View Document 1 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(71, "Light Yellow Round 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(72, "Pin Yellow 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(73, "Bug 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(74, "Stop Light Yellow Red Amber 16 h i32.ico")
        Me.imageList1.Images.SetKeyName(75, "Hammer 16 h i32.ico")
        '
        'MenuStrip1
        '
        Me.MenuStrip1.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.Flow
        Me.MenuStrip1.Location = New System.Drawing.Point(0, 0)
        Me.MenuStrip1.Name = "MenuStrip1"
        Me.MenuStrip1.Padding = New System.Windows.Forms.Padding(4, 2, 0, 2)
        Me.MenuStrip1.Size = New System.Drawing.Size(759, 23)
        Me.MenuStrip1.TabIndex = 2
        Me.MenuStrip1.Text = "MenuStrip1"
        '
        'XAccessiMenu
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(759, 533)
        Me.Controls.Add(Me.MenuStrip1)
        Me.IsMdiContainer = True
        Me.LookAndFeel.SkinName = "Office 2007 Black"
        Me.MainMenuStrip = Me.MenuStrip1
        Me.Margin = New System.Windows.Forms.Padding(2)
        Me.Name = "XAccessiMenu"
        Me.Text = "AccessiMenu"
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents MenuStrip1 As System.Windows.Forms.MenuStrip
End Class
